Implement OS and processor-type filtering
Filter out candidates that are not likely to match the current
machine's OS and processor architecture.

diff --git a/fetch-me b/fetch-me
--- a/fetch-me
+++ b/fetch-me
@@ -1,29 +1,80 @@
 #!/bin/bash
 
-# install-cmd
+# fetch-me
 
 # Install a (CLI) application directly from its github release.
 
 set -eu -o pipefail
 
+shopt -s nocasematch nocaseglob
+
 VERSION=0.1
 
-[[ ${DEBUG-} ]] && set -xv
+[[ ${TRACE-} ]] && set -xv
 
-os=$(uname -o)
-arch=$(uname -m)
-arch_regex="${arch}|${arch#a}"
+os_regex=$(uname -o | tr '[:upper:]' '[:lower:]' | sed 's@gnu/@@')
+
+arch=$(uname -m)  # aarch64 | amd64 | x86_64
+arch_regex="${arch}"
+
+if [[ $arch == *64 ]]; then
+  arch_bitness=64
+else
+  arch_bitness=32
+fi
+
 if [[ $arch == "aarch"* ]]; then
-  arch_regex="${arch_regex}|arm64"
+  arch_regex="${arch_regex}|${arch#a}|arm64"
+elif [[ $arch == @(amd64|x86_64) ]]; then
+  arch_regex="${arch_regex}|intel.?64|amd64|x86_64"
+else
+  arch_regex="${arch_regex}|intel.?32||x86|i[356]86"
 fi
 distribution=$(awk -F= '$1=="ID"{print $2}' /etc/os-release)
 
 XDG_BIN_DIR="$(readlink -f "${XDG_DATA_HOME}/../bin")"
-CACHE_DIR="${XDG_CACHE_HOME}/install-cmd"
+CACHE_DIR="${XDG_CACHE_HOME}/fetch-me"
+
+warn() {
+  echo >&2 "$@"
+}
 
 die() {
-  echo >&2 "$@"
+  warn "$@"
   exit 3
+}
+
+assert-cmd() {
+  local cmd="$1"
+  local msg="${2-}"
+  type -P "$cmd" &>/dev/null || {
+    if [[ -n $cmd ]]; then
+      warn "Warning: $cmd not installed/available. Installation"
+    else
+      die "Error: $cmd: Not found or not installed in $PATH"
+    fi
+  }
+}
+
+assert-cmd wget
+assert-cmd jq
+
+debug() {
+  if [[ ! -t 0 ]]; then
+    while read -r in; do
+      debug "$in"
+    done
+  elif [[ -n ${DEBUG-} ]]; then
+    echo >&2 "DEBUG: $@"
+  fi
+}
+
+wget() {
+  local header='-qc'
+  if [[ -n ${GITHUB_API_TOKEN-} ]]; then
+    header="--header='Authorization: token $GITHUB_API_TOKEN'"
+  fi
+  command wget -qc "${header-}" "$@"
 }
 
 get-gh-artifact() {
@@ -38,11 +89,14 @@ get-gh-artifact() {
   else
     local artifact="$cache/$type"
   fi
+  if [[ -f $artifact && ! -s $artifact ]]; then
+    rm -f "$artifact"
+  fi
   local one_day_ago=$(date -d 'now - 1 days' +%s &>/dev/null)
   local artifact_mtime=$(date -r "$artifact" +%s &>/dev/null)
   if (( artifact_mtime <= one_day_ago )); then
     rm -f "$artifact"
-    wget -qc "$url" -O "$artifact"
+    wget "$url" -O "$artifact"
   fi
   jq -Ser '.' "$artifact"
 }
@@ -54,6 +108,7 @@ get-release() {
 
 get-latest() {
   local repo="${1%/}"
+  set -xv
   get-gh-artifact "$repo" latest | jq -Ser '.tag_name'
 }
 
@@ -64,25 +119,38 @@ install-candidate() {
   local command="$4"
   local cache="$CACHE_DIR/$repo/${candidate%/*}"
   local file="$cache/${url##*/}"
-  echo
-  echo "Installing $url"
+  debug "Downloading $url"
   mkdir -p "$cache"
   wget -qc "$url" -O "$file"
 
   file_type=$(file -i "$file" | awk -F'[;: ]' '{print $3}')
+  debug "Installing  $file (type: $file_type)"
   case "$file_type" in
     application/x-executable)
-      install -m=555 "$file" "$XDG_BIN_DIR/$command"
+      assert-cmd install
+      install -m=555 "$file" "$XDG_BIN_DIR/$command" 2>&1 | debug
     ;;
     application/gzip)
+      assert-cmd tar
       tar xf "$file" -C "$cache"
       cd "$cache"
-      find . -maxdepth 1 -type f -executable -exec sh -c 'for i; do install -v -m=555 $i '"$XDG_BIN_DIR"'; done' _ {} +
+      find . -maxdepth 1 -type f -executable -exec sh -c '
+        for i; do install -v -m=555 $i '"$XDG_BIN_DIR"'; done
+      ' _ {} + 2>&1 | debug
     ;;
     application/vnd.debian.binary-package)
-      sudo apt install "$file"
+      assert-cmd sudo
+      assert-cmd apt
+      sudo apt -yqq install "$file" | debug
+    ;;
+    *)
+      warn "Error: No installation method implemented for $file ($file_type)"
+      die "Giving up. Please install $file manually."
     ;;
   esac
+
+  echo -n "$command successfully installed to "
+  hash -r && type -P "$command"
 }
 
 
@@ -94,13 +162,18 @@ show-help() {
     -t   tag/version release to install
     -c   command to install repo as
     -a   arch to use in search
-    -s   request sudo for privileged installs
+    -d   enable debug output
     -V   print version
 
 USAGE:
   $0 sharkdp/bat          # common case - bat is installed as bat
   $0 sharkdp/bat bat-cmd  # expose the command as bat-cmd(1)
   $0 sharkdp/bat -v 0.20  # specifically install v0.20
+
+ENVIRONMENT VARIABLES:
+  GITHUB_API_TOKEN  - Github PAT/API Token
+  DEBUG             - Enable debug output
+  TRACE             - Enable extended bash tracing
 EOF
 }
 
@@ -131,8 +204,7 @@ done
 repo=
 tag=
 command=
-sudo=0
-while getopts ":a:c:hst:V" opt; do
+while getopts ":a:c:dhst:V" opt; do
   case $opt in
     a)
       arch_regex="$OPTARG"
@@ -140,11 +212,11 @@ while getopts ":a:c:hst:V" opt; do
     c)
       command="$OPTARG"
     ;;
+    d)
+      DEBUG=1
+    ;;
     h)
       show-help; exit 0;
-    ;;
-    s)
-      sudo=1
     ;;
     V)
       echo "$0 $VERSION"; exit;
@@ -166,7 +238,7 @@ shift $((OPTIND-1))
 
 (( ${#args[@]} > 0 )) && set -- "${args[@]}" "$@"
 
-[[ ${DEBUG-} ]] && echo "args: $@"
+debug "args: $@"
 
 [[ -z $repo ]] && repo="$1"; shift
 repo="${repo#https://github.com/}"
@@ -178,29 +250,54 @@ repo="${repo#https://github.com/}"
 
 [[ -z $tag ]] && tag=$(get-latest "$repo")
 tag="${tag//[\+]/\\\\+}"
+tag="${tag//[\-]/\\\\-}"
 
-echo
-echo "repo:    $repo"
-echo "command: $command"
-echo "tag:     $tag"
-echo "arch:    $arch_regex"
-echo
+echo "Discovering releases of $repo"
+echo "  repo:    $repo (https://github.com/$repo)"
+echo "  command: $command ($(type -P "$command"))"
+echo "  tag:     $tag"
+echo "  arch:    $arch_regex"
 
 json=$(get-release "$repo" | jq -S '.[] | select(.tag_name|test("^v?'"$tag"'"))')
 candidates=($(
   jq -Scer '
     .assets[].browser_download_url |
-      select(.|test("'"${arch_regex}"'")) |
-      capture("download/(?<ver>.+)").ver
+        select(.|test("'"${arch_bitness}"'")) |
+        capture("download/(?<ver>.+)").ver
   ' <<<"$json" | sort
 ))
+
+if [[ ${candidates[@]} =~ $os_regex ]]; then
+  filtered=()
+  for url in ${candidates[@]}; do
+    if [[ $url =~ $os_regex ]]; then
+      debug "matching os: $url ~ $os_regex"
+      filtered+=("$url")
+    fi
+  done
+  candidates=("${filtered[@]}")
+fi
+
+if [[ ${candidates[@]} =~ $arch_regex ]]; then
+  filtered=()
+  for url in ${candidates[@]}; do
+    if [[ $url =~ $arch_regex ]]; then
+      debug "matching arch: $url ~ $arch_regex"
+      filtered+=("$url")
+    fi
+  done
+  candidates=("${filtered[@]}")
+fi
 
 if (( ${#candidates[@]} == 0 )); then
   die "No candidates found for $repo ($arch)"
 fi
 
 candidate=
-if (( ${#candidates[@]} > 0 )); then
+if (( ${#candidates[@]} == 1 )); then
+  candidate=${candidates[0]}
+  echo "Found candidate to install: $candidate"
+elif (( ${#candidates[@]} > 1 )); then
   echo "Multiple candidates found"
   for i in ${!candidates[@]}; do
     printf '%3d - %s\n' "$i" "${candidates[$i]}"
